### ISSUE TITLE
DSPy : Synthetic Data Generation

### ISSUE THREAD

**Issue by Josephrp** [Josephrp/adapt-a-rag#11]
### Issue 

Ragas takes a lot of ressources

### Solution

- We can use DSPy to [generate Synthetic Data ](https://github.com/stanfordnlp/dspy/blob/main/dspy/experimental/synthetic_data.py)
- We can use anthropic to generate synthetic data using text chunks

| prompt | answer |
|--------|--------|
| ask claude to generate a question, then append it to a text chunk | ask claude to take a text chunk and question and write a long answer |

**Comment by Ariankhalfani** [comment]
solved using DSPY data generator
