### ISSUE TITLE
DSPy : Synthetic Data Generator

### ISSUE THREAD

**Issue by Josephrp** [Josephrp/adapt-a-rag#20]
### Issues

`class SyntheticDataGenerator:` is using default  / ai generated code , and it will produce low quality outputs

### Tasks

- [x] #23
- [ ] redo the prompts for synthetic data generation
- [ ] run and debug

**Comment by Mind-Interfaces** [comment]
it could be worse.. far worse.. *hides their work*  which model did you say? more like: up for three days straight engineering that, "nah bro.. came like that in the picture frame. ai gen probly."

**Comment by Josephrp** [comment]
prompts should be :
- generate a question from the text snippet provided
- generate a description using titles and subtitles in long form format in markdown format
- json escape the results
