### ISSUE TITLE
DSPy : Basic MH ( )

### ISSUE THREAD

**Issue by Josephrp** [Josephrp/adapt-a-rag#21]
```python
            search_results = self.claude_model.search(question, context=context, k=self.passages_per_hop)
            passages = [result.passage for result in search_results]
            context = deduplicate(context + passages)

        # Generation using Claude model
        answer = self.claude_model.generate(context=context, question=question)

        return answer
```

can we actually search with claude ?

**Comment by Mind-Interfaces** [comment]
No results found for "claude_model.search". 🤷

**Comment by Mind-Interfaces** [comment]
In claude-retriver they got a built-in search and a brave search tool

https://github.com/anthropics/anthropic-retrieval-demo

**Comment by Mind-Interfaces** [comment]
https://github.com/anthropics/anthropic-retrieval-demo/blob/main/claude_retriever/searcher/searchtools/websearch.py

**Comment by Josephrp** [comment]
we should use either langchain , that what you said, or llamadindex for speed + simplicity :-)

**Comment by Josephrp** [comment]
https://github.com/Josephrp/adapt-a-rag/issues/18#issue-2189900094

related to this issue
